// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd_-5m64vFalDLjMFVXp4O-rU9bR7NBNE',
    appId: '1:776038389388:web:5f3616752a9a0cd1f50da9',
    messagingSenderId: '776038389388',
    projectId: 'fitbuddy-3b7e1',
    authDomain: 'fitbuddy-3b7e1.firebaseapp.com',
    storageBucket: 'fitbuddy-3b7e1.appspot.com',
    measurementId: 'G-LY543GZQGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5UNUff132Gzgt52AFBS8ByN_qGiMgYLs',
    appId: '1:776038389388:android:811d9804162fdf35f50da9',
    messagingSenderId: '776038389388',
    projectId: 'fitbuddy-3b7e1',
    storageBucket: 'fitbuddy-3b7e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX1LK7e9SlB5ww_jNKrpZcFoCp6vH02VA',
    appId: '1:776038389388:ios:edfc20972766d3def50da9',
    messagingSenderId: '776038389388',
    projectId: 'fitbuddy-3b7e1',
    storageBucket: 'fitbuddy-3b7e1.appspot.com',
    iosBundleId: 'com.example.fitbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX1LK7e9SlB5ww_jNKrpZcFoCp6vH02VA',
    appId: '1:776038389388:ios:edfc20972766d3def50da9',
    messagingSenderId: '776038389388',
    projectId: 'fitbuddy-3b7e1',
    storageBucket: 'fitbuddy-3b7e1.appspot.com',
    iosBundleId: 'com.example.fitbuddy',
  );
}
